# Generated by Django 5.1.3 on 2024-11-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contents',
        ),
    ]
